-- ============================================================================
-- Suplatzigram — Script de inicialización de Supabase
-- ============================================================================
-- Crea toda la estructura que necesita la app en un proyecto Supabase nuevo:
-- tablas, trigger de registro, políticas RLS, Realtime y bucket de Storage.
--
-- Cómo usarlo:
--   Opción A) Pega el contenido completo en el SQL Editor del Dashboard
--             (https://supabase.com/dashboard → tu proyecto → SQL Editor) y ejecuta.
--   Opción B) Con la CLI: supabase db push (o psql -f supabase/setup.sql)
--
-- El script es idempotente: se puede ejecutar más de una vez sin errores.
-- La Edge Function `send-notification` se despliega aparte (ver README).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Tablas
-- ----------------------------------------------------------------------------

-- Perfil 1:1 con auth.users; se crea automáticamente al registrarse (ver trigger).
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null unique,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Posts del feed. user_id no tiene FK a profiles a propósito: la app resuelve
-- los perfiles con una consulta aparte, no con embedding de PostgREST.
create table if not exists public.posts_new (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  image_url text not null,
  caption text not null default '',
  likes integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  post_id bigint not null references public.posts_new (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, post_id)
);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  post_id bigint not null references public.posts_new (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  type text not null,
  message text not null,
  post_id bigint,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists likes_post_id_idx on public.likes (post_id);
create index if not exists comments_post_id_idx on public.comments (post_id);
create index if not exists notifications_user_id_idx on public.notifications (user_id);

-- ----------------------------------------------------------------------------
-- 2. Trigger: crear el profile al registrarse un usuario
-- ----------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data->>'username', ''),
      split_part(new.email, '@', 1) || '_' || left(new.id::text, 4)
    )
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ----------------------------------------------------------------------------
-- 3. Row Level Security
-- ----------------------------------------------------------------------------
-- Lectura pública de posts/perfiles/likes/comentarios; escribir requiere sesión
-- y ser dueño de la fila; las notificaciones solo las ve su destinatario.

alter table public.profiles enable row level security;
alter table public.posts_new enable row level security;
alter table public.likes enable row level security;
alter table public.comments enable row level security;
alter table public.notifications enable row level security;

-- profiles
drop policy if exists "Public can read profiles" on public.profiles;
create policy "Public can read profiles"
  on public.profiles for select using (true);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

-- posts_new
drop policy if exists "Public can read posts" on public.posts_new;
create policy "Public can read posts"
  on public.posts_new for select using (true);

drop policy if exists "posts_insert_authenticated" on public.posts_new;
create policy "posts_insert_authenticated"
  on public.posts_new for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "posts_owner_update" on public.posts_new;
create policy "posts_owner_update"
  on public.posts_new for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "posts_owner_delete" on public.posts_new;
create policy "posts_owner_delete"
  on public.posts_new for delete to authenticated
  using ((select auth.uid()) = user_id);

-- likes
drop policy if exists "Public can read likes" on public.likes;
create policy "Public can read likes"
  on public.likes for select using (true);

drop policy if exists "Users can like as themselves" on public.likes;
create policy "Users can like as themselves"
  on public.likes for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can remove own likes" on public.likes;
create policy "Users can remove own likes"
  on public.likes for delete
  using ((select auth.uid()) = user_id);

-- comments
drop policy if exists "Public can read comments" on public.comments;
create policy "Public can read comments"
  on public.comments for select using (true);

drop policy if exists "Users can comment as themselves" on public.comments;
create policy "Users can comment as themselves"
  on public.comments for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "comments_owner_update" on public.comments;
create policy "comments_owner_update"
  on public.comments for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "comments_owner_delete" on public.comments;
create policy "comments_owner_delete"
  on public.comments for delete to authenticated
  using ((select auth.uid()) = user_id);

-- notifications (las inserta la Edge Function con service role, que salta RLS)
drop policy if exists "Users can read own notifications" on public.notifications;
create policy "Users can read own notifications"
  on public.notifications for select
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can mark own notifications read" on public.notifications;
create policy "Users can mark own notifications read"
  on public.notifications for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- ----------------------------------------------------------------------------
-- 4. Realtime (dashboard en vivo y campana de notificaciones)
-- ----------------------------------------------------------------------------

do $$
declare
  t text;
begin
  foreach t in array array['posts_new', 'profiles', 'likes', 'comments', 'notifications']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end;
$$;

-- ----------------------------------------------------------------------------
-- 5. Storage: bucket público `images` (posts/ y profile/)
-- ----------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do update set public = true;

-- Solo usuarios autenticados escriben en el bucket; el bucket es público
-- (public = true) para lectura, así que no hace falta política SELECT para
-- servir imágenes por URL. SELECT + UPDATE son necesarias para que el upsert
-- de avatares (profile/edit) pueda reemplazar un archivo existente.
drop policy if exists "Anyone can upload images" on storage.objects;

drop policy if exists "Authenticated can upload images" on storage.objects;
create policy "Authenticated can upload images"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'images');

drop policy if exists "Authenticated can read images" on storage.objects;
create policy "Authenticated can read images"
  on storage.objects for select to authenticated
  using (bucket_id = 'images');

drop policy if exists "Authenticated can update images" on storage.objects;
create policy "Authenticated can update images"
  on storage.objects for update to authenticated
  using (bucket_id = 'images')
  with check (bucket_id = 'images');

drop policy if exists "Authenticated can delete images" on storage.objects;
create policy "Authenticated can delete images"
  on storage.objects for delete to authenticated
  using (bucket_id = 'images');
