/**
 * Los tipos de dominio se derivan del schema de Drizzle (fuente de verdad),
 * expuesto por el paquete `@platzi-fc/db`.
 *
 * Uso:
 *   import type { Match, Player, Team } from '@/types';
 */
export type {
  Season,
  NewSeason,
  SeasonEstado,
  Competition,
  NewCompetition,
  CompetitionTipo,
  Team,
  NewTeam,
  TeamTipo,
  Match,
  NewMatch,
  MatchEstado,
  AlineacionEntry,
  Player,
  NewPlayer,
  PlayerPosicion,
  PlayerPieHabil,
  PlayerEstado,
  HistorialClub,
  RedesSociales,
  Staff,
  NewStaff,
  MatchEvent,
  NewMatchEvent,
  MatchEventTipo,
  PlayerSeasonStats,
  NewPlayerSeasonStats,
  Standing,
  NewStanding,
  FormaResultado,
  Article,
  NewArticle,
  ArticleCategoria,
  ArticleEstado,
  Video,
  NewVideo,
  VideoPlataforma,
  VideoCategoria,
  Gallery,
  NewGallery,
  GalleryImage,
  Page,
  NewPage,
  Product,
  NewProduct,
  ProductCategoria,
  Sponsor,
  NewSponsor,
  SponsorTier,
  Membership,
  NewMembership,
  MembershipTier,
  CommunityEvent,
  NewCommunityEvent,
  CommunityEventTipo,
  NewsletterSubscriber,
  NewNewsletterSubscriber,
  NewsletterStatus,
} from '@platzi-fc/db';
export {
  ARTICLE_CATEGORIAS,
  PRODUCT_CATEGORIAS,
  SPONSOR_TIERS,
  MEMBERSHIP_TIERS,
  COMMUNITY_EVENT_TIPOS,
} from '@platzi-fc/db';
